//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATNWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public string id { get; set; }
        public string password { get; set; }
        public decimal phone { get; set; }
        public string firs_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public string avatar { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<int> trip_count { get; set; }
        public Nullable<int> trip_accept { get; set; }
        public Nullable<int> trip_cancel { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> account_type { get; set; }
        public Nullable<int> gene { get; set; }
        public string address { get; set; }
        public string driving_licence_id { get; set; }
    }
}
