//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATNWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class triprequest
    {
        public string id { get; set; }
        public string driver_id { get; set; }
        public string car_type_id { get; set; }
        public string goods_type_id { get; set; }
        public string trip_id { get; set; }
        public double good_width { get; set; }
        public Nullable<double> good_height { get; set; }
        public Nullable<double> good_weight { get; set; }
        public string start_point { get; set; }
        public string destination { get; set; }
        public string service_id { get; set; }
        public Nullable<decimal> trip_cost { get; set; }
        public string payment_type_id { get; set; }
        public string note { get; set; }
        public Nullable<int> status { get; set; }
    }
}
