//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATNWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip
    {
        public string id { get; set; }
        public string driver_id { get; set; }
        public string customer_id { get; set; }
        public Nullable<System.DateTime> pickup_time { get; set; }
        public Nullable<System.DateTime> dropoff_time { get; set; }
        public string vehicle_id { get; set; }
        public Nullable<double> rider_rating { get; set; }
        public string driver_rating { get; set; }
        public Nullable<decimal> money_sum { get; set; }
    }
}
