//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATNWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        public string id { get; set; }
        public string firm_id { get; set; }
        public string model { get; set; }
        public string color { get; set; }
        public string company { get; set; }
        public string lience_plate { get; set; }
        public string certificate_id { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> type { get; set; }
    }
}
