//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATNWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wallet
    {
        public string id { get; set; }
        public Nullable<decimal> surplus { get; set; }
        public Nullable<decimal> debit { get; set; }
        public string account_id { get; set; }
    }
}
